
context('digest')

sequences <- c('MAASCPLPVTPDLPTLRAKLQGLLQFLRDALSISNAHTVDFYTESVWEELVDLPPETVLAALRKSASETEALPSETRPLVEAEWEAGMTDFPKIF
               CETSQKLVSVEAFALAAKYYSVQNLGICTPFEQLLVALRGNQNQRIGENQKAVEFMNMKKSHEVQAMSELISSIADYYGIKQVIDLGSGKGYLSSF
               LSLKYGLKVYGIDSSNTNTHGAEERNRKLKKHWKLCHAQSRLDVNGLALKMAKERKVQNKVKNKADTEEVFNNSPTNQEKMPTSAILPDFSGSVIS
               NIRNQMETLHSQPHQEENLCFENSFSLINLLPINAVEPTSSQQIPNRETSEANKERRKMTSKSSESNIYSPLTSFITADSELHDIIKDLEDCLMVG
               LHTCGDLAPNTLRIFTSNSEIKGVCSVGCCYHLLSEEFENQHKERTQEKWGFPMCHYLKEERWCCGRNARMSACLALERVAAGQGLPTESLFYRAV
               LQDIIKDCYGITKCDRHVGKIYSKCSSFLDYVRRSLKKLGLDESKLPEKIIMNYYEKYKPRMNELEAFNMLKVVLAPCIETLILLDRLCYLKEQED
               IAWSALVKLFDPVKSPRCYAVIALKKQQ',
               'MSFCSFFGGEVFQNHFEPGVYVCAKCGYELFSSRSKYAHSSPWPAFTETIHADSVAKRPEHNRSEALKVSCGKCGNGLGHEFLNDGPKPGQSRFC
               IFSSSLKFVPKGKETSASQGH')

ids <- c('Q8N6Q8', 'Q9NZV6')

zero_missed <- list('Q8N6Q8' = c("GNQNQR", "IGENQK", "LFDPVK", "DCYGITK", "ETSEANK", "LCHAQSR", "LGLDESK",
                                 "AVEFMNMK", "AVLQDIIK", "CYAVIALK", "IFCETSQK", "IIMNYYEK", "CSSFLDYVR",
                                 "IFTSNSEIK", "LDVNGLALK", "LQGLLQFLR", "MSACLALER", "QVIDLGSGK", "GYLSSFLSLK",
                                 "WGFPMCHYLK", "MNELEAFNMLK", "EQEDIAWSALVK", "LVSVEAFALAAK", "VAAGQGLPTESLFYR",
                                 "VVLAPCIETLILLDR", "ADTEEVFNNSPTNQEK", "MAASCPLPVTPDLPTLR", "VYGIDSSNTNTHGAEER",
                                 "MPTSAILPDFSGSVISNIR", "GVCSVGCCYHLLSEEFENQHK", "SHEVQAMSELISSIADYYGIK",
                                 "YYSVQNLGICTPFEQLLVALR", "DLEDCLMVGLHTCGDLAPNTLR", "SSESNIYSPLTSFITADSELHDIIK",
                                 "SASETEALPSETRPLVEAEWEAGMTDFPK", "DALSISNAHTVDFYTESVWEELVDLPPETVLAALR",
                                 "NQMETLHSQPHQEENLCFENSFSLINLLPINAVEPTSSQQIPNR"),
                   'Q9NZV6' = c("RPEHNR", "ETSASQGH", "CGYELFSSR", "FCIFSSSLK", "CGNGLGHEFLNDGPKPGQSR",
                                "YAHSSPWPAFTETIHADSVAK", "MSFCSFFGGEVFQNHFEPGVYVCAK"))

one_missed <- list('Q8N6Q8' = c("ERTQEK", "GNQNQR", "IGENQK", "LFDPVK", "VQNKVK", "CDRHVGK", "DCYGITK", "ETSEANK",
                                "LCHAQSR", "LGLDESK", "AVEFMNMK", "AVLQDIIK", "CYAVIALK", "EERWCCGR", "HVGKIYSK", 
                                "IFCETSQK", "IIMNYYEK", "KLGLDESK", "WCCGRNAR", "AVEFMNMKK", "CSSFLDYVR", "CYAVIALKK", 
                                "ETSEANKER", "IFTSNSEIK", "LDVNGLALK", "LFDPVKSPR", "LQGLLQFLR", "MSACLALER", 
                                "QVIDLGSGK", "CSSFLDYVRR", "DCYGITKCDR", "GYLSSFLSLK", "HWKLCHAQSR", "WGFPMCHYLK", 
                                "AKLQGLLQFLR", "LGLDESKLPEK", "MNELEAFNMLK", "SPRCYAVIALK", "EQEDIAWSALVK", 
                                "GNQNQRIGENQK", "IIMNYYEKYKPR", "LDVNGLALKMAK", "LPEKIIMNYYEK", "LVSVEAFALAAK", 
                                "NARMSACLALER", "IYSKCSSFLDYVR", "WGFPMCHYLKEER", "GYLSSFLSLKYGLK", "IGENQKAVEFMNMK",
                                "TQEKWGFPMCHYLK", "AVLQDIIKDCYGITK", "VAAGQGLPTESLFYR", "VVLAPCIETLILLDR", 
                                "YKPRMNELEAFNMLK", "ADTEEVFNNSPTNQEK", "LCHAQSRLDVNGLALK", "LCYLKEQEDIAWSALVK", 
                                "MAASCPLPVTPDLPTLR", "VYGIDSSNTNTHGAEER", "EQEDIAWSALVKLFDPVK", "NKADTEEVFNNSPTNQEK", 
                                "MAASCPLPVTPDLPTLRAK", "MPTSAILPDFSGSVISNIR", "QVIDLGSGKGYLSSFLSLK", "VYGIDSSNTNTHGAEERNR", 
                                "IFCETSQKLVSVEAFALAAK", "VVLAPCIETLILLDRLCYLK", "GVCSVGCCYHLLSEEFENQHK", 
                                "SHEVQAMSELISSIADYYGIK", "YGLKVYGIDSSNTNTHGAEER", "YYSVQNLGICTPFEQLLVALR",
                                "DLEDCLMVGLHTCGDLAPNTLR", "KSHEVQAMSELISSIADYYGIK", "GVCSVGCCYHLLSEEFENQHKER", 
                                "VAAGQGLPTESLFYRAVLQDIIK", "MSACLALERVAAGQGLPTESLFYR", "SSESNIYSPLTSFITADSELHDIIK", 
                                "MNELEAFNMLKVVLAPCIETLILLDR", "YYSVQNLGICTPFEQLLVALRGNQNQR", 
                                "MTSKSSESNIYSPLTSFITADSELHDIIK", "SASETEALPSETRPLVEAEWEAGMTDFPK", 
                                "IFTSNSEIKGVCSVGCCYHLLSEEFENQHK", "KSASETEALPSETRPLVEAEWEAGMTDFPK", 
                                "SHEVQAMSELISSIADYYGIKQVIDLGSGK", "DLEDCLMVGLHTCGDLAPNTLRIFTSNSEIK", 
                                "LVSVEAFALAAKYYSVQNLGICTPFEQLLVALR", "ADTEEVFNNSPTNQEKMPTSAILPDFSGSVISNIR", 
                                "DALSISNAHTVDFYTESVWEELVDLPPETVLAALR", "DALSISNAHTVDFYTESVWEELVDLPPETVLAALRK",
                                "SASETEALPSETRPLVEAEWEAGMTDFPKIFCETSQK", "LQGLLQFLRDALSISNAHTVDFYTESVWEELVDLPPETVLAALR", 
                                "NQMETLHSQPHQEENLCFENSFSLINLLPINAVEPTSSQQIPNR", "SSESNIYSPLTSFITADSELHDIIKDLEDCLMVGLHTCGDLAPNTLR"),
                   'Q9NZV6' = c("FVPKGK", "RPEHNR", "ETSASQGH", "CGYELFSSR", "FCIFSSSLK", "GKETSASQGH",
                                "SEALKVSCGK", "CGYELFSSRSK", "RPEHNRSEALK", "FCIFSSSLKFVPK", "CGNGLGHEFLNDGPKPGQSR",
                                "YAHSSPWPAFTETIHADSVAK", "SKYAHSSPWPAFTETIHADSVAK", "MSFCSFFGGEVFQNHFEPGVYVCAK",
                                "VSCGKCGNGLGHEFLNDGPKPGQSR", "YAHSSPWPAFTETIHADSVAKRPEHNR",
                                "CGNGLGHEFLNDGPKPGQSRFCIFSSSLK", "MSFCSFFGGEVFQNHFEPGVYVCAKCGYELFSSR"))

two_missed <- list('Q8N6Q8' = c("ERTQEK", "GNQNQR", "IGENQK", "LFDPVK", "LKKHWK", "MAKERK", "RKMTSK", "VQNKVK",
                                "CDRHVGK", "DCYGITK", "ERKVQNK", "ETSEANK", "KVQNKVK", "LCHAQSR", "LGLDESK",
                                "AVEFMNMK", "AVLQDIIK", "CYAVIALK", "EERWCCGR", "HVGKIYSK", "IFCETSQK", "IIMNYYEK",
                                "KLGLDESK", "VQNKVKNK", "WCCGRNAR", "AVEFMNMKK", "CSSFLDYVR", "CYAVIALKK",
                                "ETSEANKER", "IFTSNSEIK", "LDVNGLALK", "LFDPVKSPR", "LQGLLQFLR", "MSACLALER",
                                "QVIDLGSGK", "CSSFLDYVRR", "DCYGITKCDR", "ETSEANKERR", "GYLSSFLSLK", "HWKLCHAQSR",
                                "WGFPMCHYLK", "AKLQGLLQFLR", "CDRHVGKIYSK", "CYAVIALKKQQ", "EERWCCGRNAR",
                                "KHWKLCHAQSR", "LGLDESKLPEK", "MNELEAFNMLK", "SLKKLGLDESK", "SPRCYAVIALK",
                                "EQEDIAWSALVK", "GNQNQRIGENQK", "IIMNYYEKYKPR", "KLGLDESKLPEK", "LDVNGLALKMAK",
                                "LPEKIIMNYYEK", "LVSVEAFALAAK", "NARMSACLALER", "SPRCYAVIALKK", "CSSFLDYVRRSLK",
                                "IYSKCSSFLDYVR", "WGFPMCHYLKEER", "DCYGITKCDRHVGK", "GYLSSFLSLKYGLK", "IGENQKAVEFMNMK",
                                "IYSKCSSFLDYVRR", "LDVNGLALKMAKER", "TQEKWGFPMCHYLK", "AVLQDIIKDCYGITK",
                                "IGENQKAVEFMNMKK", "VAAGQGLPTESLFYR", "VVLAPCIETLILLDR", "YKPRMNELEAFNMLK",
                                "ADTEEVFNNSPTNQEK", "ERTQEKWGFPMCHYLK", "LCHAQSRLDVNGLALK", "LPEKIIMNYYEKYKPR",
                                "HVGKIYSKCSSFLDYVR", "LCYLKEQEDIAWSALVK", "LFDPVKSPRCYAVIALK", "MAASCPLPVTPDLPTLR",
                                "TQEKWGFPMCHYLKEER", "VYGIDSSNTNTHGAEER", "WCCGRNARMSACLALER", "AVLQDIIKDCYGITKCDR",
                                "EQEDIAWSALVKLFDPVK", "NKADTEEVFNNSPTNQEK", "WGFPMCHYLKEERWCCGR", "HWKLCHAQSRLDVNGLALK", 
                                "LCHAQSRLDVNGLALKMAK", "LGLDESKLPEKIIMNYYEK", "MAASCPLPVTPDLPTLRAK", "MPTSAILPDFSGSVISNIR",
                                "QVIDLGSGKGYLSSFLSLK", "VYGIDSSNTNTHGAEERNR", "GNQNQRIGENQKAVEFMNMK", "IFCETSQKLVSVEAFALAAK",
                                "VKNKADTEEVFNNSPTNQEK", "VVLAPCIETLILLDRLCYLK", "VYGIDSSNTNTHGAEERNRK", 
                                "EQEDIAWSALVKLFDPVKSPR", "GVCSVGCCYHLLSEEFENQHK", "SHEVQAMSELISSIADYYGIK", 
                                "YGLKVYGIDSSNTNTHGAEER", "YYSVQNLGICTPFEQLLVALR", "DLEDCLMVGLHTCGDLAPNTLR", 
                                "KSHEVQAMSELISSIADYYGIK", "GVCSVGCCYHLLSEEFENQHKER", "IIMNYYEKYKPRMNELEAFNMLK", 
                                "LCYLKEQEDIAWSALVKLFDPVK", "QVIDLGSGKGYLSSFLSLKYGLK", "VAAGQGLPTESLFYRAVLQDIIK", 
                                "YGLKVYGIDSSNTNTHGAEERNR", "MSACLALERVAAGQGLPTESLFYR", "SSESNIYSPLTSFITADSELHDIIK",
                                "MNELEAFNMLKVVLAPCIETLILLDR", "GVCSVGCCYHLLSEEFENQHKERTQEK", "NARMSACLALERVAAGQGLPTESLFYR",
                                "YYSVQNLGICTPFEQLLVALRGNQNQR", "MAASCPLPVTPDLPTLRAKLQGLLQFLR", "MTSKSSESNIYSPLTSFITADSELHDIIK",
                                "SASETEALPSETRPLVEAEWEAGMTDFPK", "AVEFMNMKKSHEVQAMSELISSIADYYGIK", "IFTSNSEIKGVCSVGCCYHLLSEEFENQHK",
                                "KMTSKSSESNIYSPLTSFITADSELHDIIK", "KSASETEALPSETRPLVEAEWEAGMTDFPK", "SHEVQAMSELISSIADYYGIKQVIDLGSGK", 
                                "VAAGQGLPTESLFYRAVLQDIIKDCYGITK", "YKPRMNELEAFNMLKVVLAPCIETLILLDR", "DLEDCLMVGLHTCGDLAPNTLRIFTSNSEIK", 
                                "GYLSSFLSLKYGLKVYGIDSSNTNTHGAEER", "KSHEVQAMSELISSIADYYGIKQVIDLGSGK", 
                                "MNELEAFNMLKVVLAPCIETLILLDRLCYLK", "IFTSNSEIKGVCSVGCCYHLLSEEFENQHKER", "MSACLALERVAAGQGLPTESLFYRAVLQDIIK", 
                                "VVLAPCIETLILLDRLCYLKEQEDIAWSALVK", "LVSVEAFALAAKYYSVQNLGICTPFEQLLVALR", 
                                "YYSVQNLGICTPFEQLLVALRGNQNQRIGENQK", "ADTEEVFNNSPTNQEKMPTSAILPDFSGSVISNIR",
                                "DALSISNAHTVDFYTESVWEELVDLPPETVLAALR", "DALSISNAHTVDFYTESVWEELVDLPPETVLAALRK",
                                "NKADTEEVFNNSPTNQEKMPTSAILPDFSGSVISNIR", "SASETEALPSETRPLVEAEWEAGMTDFPKIFCETSQK",
                                "KSASETEALPSETRPLVEAEWEAGMTDFPKIFCETSQK", "LVSVEAFALAAKYYSVQNLGICTPFEQLLVALRGNQNQR",
                                "SHEVQAMSELISSIADYYGIKQVIDLGSGKGYLSSFLSLK", "IFCETSQKLVSVEAFALAAKYYSVQNLGICTPFEQLLVALR", 
                                "LQGLLQFLRDALSISNAHTVDFYTESVWEELVDLPPETVLAALR", "NQMETLHSQPHQEENLCFENSFSLINLLPINAVEPTSSQQIPNR", 
                                "LQGLLQFLRDALSISNAHTVDFYTESVWEELVDLPPETVLAALRK", "AKLQGLLQFLRDALSISNAHTVDFYTESVWEELVDLPPETVLAALR",
                                "SSESNIYSPLTSFITADSELHDIIKDLEDCLMVGLHTCGDLAPNTLR",
                                "SASETEALPSETRPLVEAEWEAGMTDFPKIFCETSQKLVSVEAFALAAK"),
                   'Q9NZV6' = c("FVPKGK", "RPEHNR", "ETSASQGH", "CGYELFSSR", "FCIFSSSLK", "GKETSASQGH", "SEALKVSCGK",
                                "CGYELFSSRSK", "RPEHNRSEALK", "FCIFSSSLKFVPK", "FVPKGKETSASQGH", "FCIFSSSLKFVPKGK",
                                "RPEHNRSEALKVSCGK", "CGNGLGHEFLNDGPKPGQSR", "YAHSSPWPAFTETIHADSVAK",
                                "SKYAHSSPWPAFTETIHADSVAK", "MSFCSFFGGEVFQNHFEPGVYVCAK", "VSCGKCGNGLGHEFLNDGPKPGQSR",
                                "YAHSSPWPAFTETIHADSVAKRPEHNR", "CGNGLGHEFLNDGPKPGQSRFCIFSSSLK",
                                "SKYAHSSPWPAFTETIHADSVAKRPEHNR", "SEALKVSCGKCGNGLGHEFLNDGPKPGQSR",
                                "CGYELFSSRSKYAHSSPWPAFTETIHADSVAK", "YAHSSPWPAFTETIHADSVAKRPEHNRSEALK",
                                "CGNGLGHEFLNDGPKPGQSRFCIFSSSLKFVPK", "MSFCSFFGGEVFQNHFEPGVYVCAKCGYELFSSR",
                                "VSCGKCGNGLGHEFLNDGPKPGQSRFCIFSSSLK", "MSFCSFFGGEVFQNHFEPGVYVCAKCGYELFSSRSK"))

residueAtoms = system.file('defaultResidueAtoms.txt', package = 'peptideUtils', mustWork = T)

test_that('mz filter works',{
  expect_equal(digest(sequences, ids, nMissedCleavages = 0, maxCharge = 3,
    residueAtoms = residueAtoms), zero_missed)
  expect_equal(digest(sequences, ids, nMissedCleavages = 1, maxCharge = 3,
    residueAtoms = residueAtoms), one_missed)
  expect_equal(digest(sequences, ids, nMissedCleavages = 2, maxCharge = 3,
    residueAtoms = residueAtoms), two_missed)
})

test_that('length filter works', {
  expect_equal(digest('GKGGGGGA', 'rando', mz_filter = F), list('rando' = 'GGGGGA'))
  expect_equal(digest('GKGGGGGA', 'rando', mz_filter = F, minLen = 7), list('rando' = character(0)))
  expect_equal(digest('GKGGGGGARTTTTTTTTTTTTTTTTTT', 'rando', mz_filter = F, maxLen = 15), list('rando' = 'GGGGGAR'))
  expect_equal(digest('GKGGGGGA', 'rando', mz_filter = T,
    residueAtoms = residueAtoms), list('rando' = character(0)))
})

test_that('Argument checks work',{
  expect_error(digest(sequences, c('rando'), mz_filter = F))
})

#dat <- data.frame(id = character(0), seq = character(0), mc = integer(0), stringsAsFactors = F)
#for(i in c(0:2)){
#  d <- digest(sequences, ids, nMissedCleavages = i, maxCharge = 3)
#  
#  for(n in names(d)){
#    temp <- data.frame(seq = d[[n]], stringsAsFactors = F)
#    temp$id <- n
#    temp$mc <- i
#    temp$len <- nchar(temp$seq)
#    dat <- rbind(dat, temp)
#  }
#}
