// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getSquences
Rcpp::CharacterVector getSquences(std::string fastaPath, const Rcpp::CharacterVector& ids);
RcppExport SEXP _peptideUtils_getSquences(SEXP fastaPathSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastaPath(fastaPathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(getSquences(fastaPath, ids));
    return rcpp_result_gen;
END_RCPP
}
// getModifiedResidues
Rcpp::CharacterVector getModifiedResidues(std::string fastaPath, const Rcpp::CharacterVector& ids, const Rcpp::CharacterVector& peptideSeq, std::string modSep);
RcppExport SEXP _peptideUtils_getModifiedResidues(SEXP fastaPathSEXP, SEXP idsSEXP, SEXP peptideSeqSEXP, SEXP modSepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastaPath(fastaPathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type peptideSeq(peptideSeqSEXP);
    Rcpp::traits::input_parameter< std::string >::type modSep(modSepSEXP);
    rcpp_result_gen = Rcpp::wrap(getModifiedResidues(fastaPath, ids, peptideSeq, modSep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_peptideUtils_getSquences", (DL_FUNC) &_peptideUtils_getSquences, 2},
    {"_peptideUtils_getModifiedResidues", (DL_FUNC) &_peptideUtils_getModifiedResidues, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_peptideUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
