// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getSquences
Rcpp::CharacterVector getSquences(std::string fastaPath, const Rcpp::CharacterVector& ids);
RcppExport SEXP _peptideUtils_getSquences(SEXP fastaPathSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastaPath(fastaPathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(getSquences(fastaPath, ids));
    return rcpp_result_gen;
END_RCPP
}
// getModifiedResidues
Rcpp::CharacterVector getModifiedResidues(std::string fastaPath, const Rcpp::CharacterVector& ids, const Rcpp::CharacterVector& peptideSeq, std::string modSep);
RcppExport SEXP _peptideUtils_getModifiedResidues(SEXP fastaPathSEXP, SEXP idsSEXP, SEXP peptideSeqSEXP, SEXP modSepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fastaPath(fastaPathSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type peptideSeq(peptideSeqSEXP);
    Rcpp::traits::input_parameter< std::string >::type modSep(modSepSEXP);
    rcpp_result_gen = Rcpp::wrap(getModifiedResidues(fastaPath, ids, peptideSeq, modSep));
    return rcpp_result_gen;
END_RCPP
}
// combineMods
std::string combineMods(const Rcpp::CharacterVector& mods, char sep);
RcppExport SEXP _peptideUtils_combineMods(SEXP modsSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type mods(modsSEXP);
    Rcpp::traits::input_parameter< char >::type sep(sepSEXP);
    rcpp_result_gen = Rcpp::wrap(combineMods(mods, sep));
    return rcpp_result_gen;
END_RCPP
}
// calcMass
Rcpp::NumericVector calcMass(const Rcpp::StringVector& sequences, bool monoMass, std::string residueAtoms, std::string atomMasses);
RcppExport SEXP _peptideUtils_calcMass(SEXP sequencesSEXP, SEXP monoMassSEXP, SEXP residueAtomsSEXP, SEXP atomMassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< bool >::type monoMass(monoMassSEXP);
    Rcpp::traits::input_parameter< std::string >::type residueAtoms(residueAtomsSEXP);
    Rcpp::traits::input_parameter< std::string >::type atomMasses(atomMassesSEXP);
    rcpp_result_gen = Rcpp::wrap(calcMass(sequences, monoMass, residueAtoms, atomMasses));
    return rcpp_result_gen;
END_RCPP
}
// calcFormula
Rcpp::StringVector calcFormula(const Rcpp::StringVector& sequences, bool subscripts, std::string residueAtoms, std::string atomMasses);
RcppExport SEXP _peptideUtils_calcFormula(SEXP sequencesSEXP, SEXP subscriptsSEXP, SEXP residueAtomsSEXP, SEXP atomMassesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< bool >::type subscripts(subscriptsSEXP);
    Rcpp::traits::input_parameter< std::string >::type residueAtoms(residueAtomsSEXP);
    Rcpp::traits::input_parameter< std::string >::type atomMasses(atomMassesSEXP);
    rcpp_result_gen = Rcpp::wrap(calcFormula(sequences, subscripts, residueAtoms, atomMasses));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_peptideUtils_getSquences", (DL_FUNC) &_peptideUtils_getSquences, 2},
    {"_peptideUtils_getModifiedResidues", (DL_FUNC) &_peptideUtils_getModifiedResidues, 4},
    {"_peptideUtils_combineMods", (DL_FUNC) &_peptideUtils_combineMods, 2},
    {"_peptideUtils_calcMass", (DL_FUNC) &_peptideUtils_calcMass, 4},
    {"_peptideUtils_calcFormula", (DL_FUNC) &_peptideUtils_calcFormula, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_peptideUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
